logging:
  level:
    com.example.consumingwebservice: INFO
    org.springframework.ws: DEBUG
    org.springframework.ws.client.MessageTracing.sent: TRACE
    org.springframework.ws.client.MessageTracing.received: TRACE

com:
  example:
    country:
      ws:
        uri: http://172.17.102.67:8080/ws/countries.wsdl



